
# Теория Кодирования
## Лабораторная работа 2

От студента группы **6405**-010302
**Слеповичева Святослава**


---

### Задание Часть 1.
#### 2.1. Сформировать порождающую матрицу линейного кода (7, 4, 3)

In [1]:
import numpy as np

n, k, d = 7, 4, 3

linear_code = np.zeros((k, n), dtype=int)
linear_code[0:k, 0:k] = np.eye(k)

linear_code[0, 4:] = np.array([1, 1, 0])
linear_code[1, 4:] = np.array([1, 0, 1])
linear_code[2, 4:] = np.array([0, 1, 1])
linear_code[3, 4:] = np.array([1, 1, 1])
print(linear_code)

[[1 0 0 0 1 1 0]
 [0 1 0 0 1 0 1]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 1 1]]


#### 2.2 Сформировать проверочную матрицу на основе порождающей.

In [2]:
# В прошлой лабораторной называлась h_matrix для удобства сохраним основные названия
h_matrix = np.zeros((n - k, n), dtype=int)

h_matrix[:, :k] = linear_code[:, k:].T  # Транспонированная часть X
h_matrix[:, k:] = np.eye(n - k, dtype=int)
print(h_matrix)

[[1 1 0 1 1 0 0]
 [1 0 1 1 0 1 0]
 [0 1 1 1 0 0 1]]


#### 2.3 Сформировать таблицу синдромов для всех однократных ошибок.

In [3]:
syndrome_table = {}
for i in range(n):
    error = np.zeros(n, dtype=int)
    error[i] = 1
    syndrome = (h_matrix @ error) % 2
    syndrome_table[tuple(syndrome)] = error
print(syndrome_table)

{(1, 1, 0): array([1, 0, 0, 0, 0, 0, 0]), (1, 0, 1): array([0, 1, 0, 0, 0, 0, 0]), (0, 1, 1): array([0, 0, 1, 0, 0, 0, 0]), (1, 1, 1): array([0, 0, 0, 1, 0, 0, 0]), (1, 0, 0): array([0, 0, 0, 0, 1, 0, 0]), (0, 1, 0): array([0, 0, 0, 0, 0, 1, 0]), (0, 0, 1): array([0, 0, 0, 0, 0, 0, 1])}


#### 2.4. Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово.
Вычислить синдром, исправить ошибку с использованием таблицы синдромов.
Убедиться в правильности полученного слова.

In [4]:
word = np.array([1, 1, 1, 1], dtype=int)
res = (word @ linear_code) % 2

print(f"Unbroken word = {res}")

broken_word = res.copy()
broken_word[1] ^= 1  # Инвертируем бит
print(f"Broken word = {broken_word}")

syndrome = (h_matrix @ broken_word) % 2
print(f"Syndrome = {syndrome}")

error_vector = syndrome_table.get(tuple(syndrome), np.zeros(n, dtype=int))
fixed_word = (broken_word + error_vector) % 2
print(f"Fixed word = {fixed_word}")

print("Correction successful =", np.array_equal(fixed_word, res))

Unbroken word = [1 1 1 1 1 1 1]
Broken word = [1 0 1 1 1 1 1]
Syndrome = [1 0 1]
Fixed word = [1 1 1 1 1 1 1]
Correction successful = True


#### 2.5. Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово.
Вычислить синдром, исправить ошибку с использованием таблицы синдромов.
Убедиться, что полученное слово отличается от отправленного.


In [5]:

broken_word[2] ^= 1  # Вторая ошибка
print(f"Broken word with double error = {broken_word}")

syndrome = (h_matrix @ broken_word) % 2
print(f"Syndrome = {syndrome}")

error_vector = syndrome_table.get(tuple(syndrome), np.zeros(n, dtype=int))
fixed_word = (broken_word + error_vector) % 2
print(f"Fixed word = {fixed_word}")

print("Correction failed (as expected) = ", not np.array_equal(fixed_word, res))

Broken word with double error = [1 0 0 1 1 1 1]
Syndrome = [1 1 0]
Fixed word = [0 0 0 1 1 1 1]
Correction failed (as expected) =  True


### Часть 2.
#### 2.6. Сформировать порождающую матрицу линейного кода (n, k, 5).

In [6]:
n, k, d = 12, 4, 5

linear_code = np.zeros((k, n), dtype=int)
linear_code[0:k, 0:k] = np.eye(k, dtype=int)

linear_code[0, 4:] = np.array([1, 1, 1, 1, 0, 0, 0, 0])
linear_code[1, 4:] = np.array([0, 0, 0, 0, 1, 1, 1, 1])
linear_code[2, 4:] = np.array([0, 0, 1, 1, 0, 0, 1, 1])
linear_code[3, 4:] = np.array([1, 0, 1, 0, 1, 0, 1, 0])

print(linear_code)

[[1 0 0 0 1 1 1 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 1 1 1]
 [0 0 1 0 0 0 1 1 0 0 1 1]
 [0 0 0 1 1 0 1 0 1 0 1 0]]


#### 2.7 Сформировать проверочную матрицу на основе порождающей.

In [7]:
h_matrix = np.zeros((n - k, n), dtype=int)

h_matrix[:, :k] = linear_code[:, k:].T
h_matrix[:, k:] = np.eye(n - k, dtype=int)
print(h_matrix)

[[1 0 0 1 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 0]
 [1 0 1 1 0 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 1 0 0 0 0]
 [0 1 0 1 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 0 0]
 [0 1 1 1 0 0 0 0 0 0 1 0]
 [0 1 1 0 0 0 0 0 0 0 0 1]]


#### 2.8 Сформировать таблицу синдромов для всех однократных и двукратных ошибок.

In [8]:
syndromes = {}

# Однократные ошибки
for i in range(n):
    error = np.zeros(n, dtype=int)
    error[i] = 1
    syndrome = (h_matrix @ error) % 2
    syndromes[tuple(syndrome)] = error

# Двукратные ошибки
for i in range(n):
    for j in range(i + 1, n):
        error = np.zeros(n, dtype=int)
        error[i] = 1
        error[j] = 1
        syndrome = (h_matrix @ error) % 2
        syndromes[tuple(syndrome)] = error

print(syndromes)

{(1, 1, 1, 1, 0, 0, 0, 0): array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), (0, 0, 0, 0, 1, 1, 1, 1): array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), (0, 0, 1, 1, 0, 0, 1, 1): array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), (1, 0, 1, 0, 1, 0, 1, 0): array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]), (1, 0, 0, 0, 0, 0, 0, 0): array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]), (0, 1, 0, 0, 0, 0, 0, 0): array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]), (0, 0, 1, 0, 0, 0, 0, 0): array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]), (0, 0, 0, 1, 0, 0, 0, 0): array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]), (0, 0, 0, 0, 1, 0, 0, 0): array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]), (0, 0, 0, 0, 0, 1, 0, 0): array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]), (0, 0, 0, 0, 0, 0, 1, 0): array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]), (0, 0, 0, 0, 0, 0, 0, 1): array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), (1, 1, 1, 1, 1, 1, 1, 1): array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), (1, 1, 0, 0, 0, 0, 1, 1): array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), (0, 1

#### 2.9. Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.

In [9]:
word = np.array([1, 0, 1, 1], dtype=int)
res = (word @ linear_code) % 2

print(f"Unbroken word = {res}")

broken_word = res.copy()
broken_word[0] ^= 1
print(f"Broken word = {broken_word}")

syndrome = (h_matrix @ broken_word) % 2
print(f"Syndrome = {syndrome}")

error_vector = syndromes.get(tuple(syndrome), np.zeros(n, dtype=int))
fixed_word = (broken_word + error_vector) % 2
print(f"Fixed word = {fixed_word}")

print("Correction successful = ", np.array_equal(fixed_word, res))

Unbroken word = [1 0 1 1 0 1 1 0 1 0 0 1]
Broken word = [0 0 1 1 0 1 1 0 1 0 0 1]
Syndrome = [1 1 1 1 0 0 0 0]
Fixed word = [1 0 1 1 0 1 1 0 1 0 0 1]
Correction successful =  True


#### 2.10. Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.

In [10]:
word = np.array([1, 0, 1, 1], dtype=int)
res = (word @ linear_code) % 2

print(f"Unbroken word = {res}")

broken_word = res.copy()
broken_word[0] ^= 1
broken_word[1] ^= 1
print(f"Broken word = {broken_word}")

syndrome = (h_matrix @ broken_word) % 2
print(f"Syndrome = {syndrome}")

error_vector = syndromes.get(tuple(syndrome), np.zeros(n, dtype=int))
fixed_word = (broken_word + error_vector) % 2
print(f"Fixed word = {fixed_word}")

print("Correction failed (as expected) = ", not np.array_equal(fixed_word, res))

Unbroken word = [1 0 1 1 0 1 1 0 1 0 0 1]
Broken word = [0 1 1 1 0 1 1 0 1 0 0 1]
Syndrome = [1 1 1 1 1 1 1 1]
Fixed word = [1 0 1 1 0 1 1 0 1 0 0 1]
Correction failed (as expected) =  False


#### 2.1. Сформировать кодовое слово длины n из слова длины k. Внести трёхкратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться, что полученное слово отличается от отправленного.

In [11]:
#### 2.11. Внесение трёхкратной ошибки и проверка результата.

# Исходное кодовое слово длины n

word = np.array([1, 0, 1, 1], dtype=int)
res = (word @ linear_code) % 2

print(f"Unbroken word = {res}")

broken_word = res.copy()
broken_word[0] ^= 1
broken_word[1] ^= 1
broken_word[2] ^= 1
print(f"Broken word = {broken_word}")

syndrome = (h_matrix @ broken_word) % 2
print(f"Syndrome = {syndrome}")

# Попытка исправления трёхкратной ошибки
try:
    error = syndromes[np.array_str(syndrome)]
except KeyError:
    print("Error detected, but cannot be corrected.")
else:
    print(f"Error = {error}")
    for i in range(len(error)):
        if error[i] == 1:
            broken_word[i] = 1 - broken_word[i]

# Проверка: отличается ли исправленное слово от исходного
is_correct = all(broken_word == word)
print(f"Corrected word matches original = {is_correct}")

Unbroken word = [1 0 1 1 0 1 1 0 1 0 0 1]
Broken word = [0 1 0 1 0 1 1 0 1 0 0 1]
Syndrome = [1 1 0 0 1 1 0 0]
Error detected, but cannot be corrected.


ValueError: operands could not be broadcast together with shapes (12,) (4,) 