
# Теория Кодирования
## Лабораторная работа 3

От студента группы **6405**-010302
**Слеповичева Святослава**


---

### Задание
#### 3.1 Написать функцию формирования порождающей и проверочной матриц кода Хэмминга
(2^r^ - 1,2^r^ − r − 1,3) на основе параметра r,
а также таблицы синдромов для всех однократных ошибок.

In [114]:
import numpy as np

# Так же, как и в первой ЛР, используется для "фокусов"
import itertools


def create_h_matrix(r_param):
    '''
    Функция, возвращающая **проверочную** матрицу Хемминга на основе параметра r
    :param r_param: параметр для создания матрицы
    :return: проверочная матрица Хемминга (h_matrix)
    '''
    i = 0
    h_matrix_local = np.zeros((2 ** r_param - 1, r_param), dtype=int)
    h_matrix_local[2 ** r_param - 1 - r_param: (2 ** r_param - 1)] = np.eye(r_param, dtype=int)
    all_r_words = [*itertools.product(range(2), repeat=r_param)]

    for element in all_r_words:
        if sum(element) > 1:
            h_matrix_local[i, :] = element
            i += 1

    return h_matrix_local


def create_g_matrix(r_param):
    '''
    Функция, возвращающая порождающую матрицу Хемминга на основе параметра r
    :param r_param: параметр для создания матрицы
    :return: порождающая матрица Хемминга
    '''

    n = 2 ** r_param - 1
    g_matrix_local = np.zeros((n - r_param, n), dtype=int)
    g_matrix_local[:, 0: (n - r_param)] = np.eye(n - r_param, dtype=int)
    g_matrix_local[:, n - r_param:] = h_matrix[0: (2 ** r_param - 1 - r_param), :].copy()
    return g_matrix_local


def create_syndrome_ones_table(h_matrix_local):
    '''
    Функция, возвращающая таблицу синдромов для **однократных** ошибок
    :param h_matrix_local: Проверочная матрица
    :return: таблица однократных синдромов
    '''

    syndromes_ones_local = {}
    for i in range(len(h_matrix_local)):
        syndromes_ones_local[np.array_str(h_matrix_local[i, :])] = i
    return syndromes_ones_local

# Зададим r пока здесь
r = 3

h_matrix = create_h_matrix(r)
g_matrix = create_g_matrix(r)
syndromes_ones = create_syndrome_ones_table(h_matrix)

print("h matrix = ")
print(h_matrix)
print("\n g_matrix = ")
print(g_matrix)


word = np.zeros(2** r - 1 - r, dtype=int)

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = 1

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

all(key_word == repaired_word)

h matrix = 
[[0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]

 g_matrix = 
[[1 0 0 0 0 1 1]
 [0 1 0 0 1 0 1]
 [0 0 1 0 1 1 0]
 [0 0 0 1 1 1 1]]


True

#### 3.2. Провести исследование кода Хэмминга для одно-, двух- и трёхкратных ошибок
для r = 2, 3, 4.

---

##### r = 3
(Просто с трёх проще начинать)

In [115]:

r = 3

# Однократная ошибка
# r = 3
word = np.zeros(2** r - 1 - r, dtype=int)

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = 1

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r3_one = all(key_word == repaired_word)


# Двукратная ошибка (не сработает)
# r = 3

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r3_two = all(key_word == repaired_word)


# Трёхкратная ошибка
# r = 3

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[3] = (broken_key_word[3] + 1) % 2

if all(((broken_key_word @ h_matrix) % 2) == np.zeros(r, dtype=int)):
    print(f"Syndrome: {(broken_key_word @ h_matrix) % 2}")
    print(f"Sent word: {key_word}")
    print(f"Broken word: {broken_key_word}")
else:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r3_three_first = all(key_word == repaired_word)


# И те же действия, но уже для другого исхода if.
# (попытаемся, но получим новое слово из-за слишком большого расстояния)
word = np.zeros(2 ** r - 1 - r, dtype=int)

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[2] = (broken_key_word[2] + 1) % 2

if all(((broken_key_word @ h_matrix) % 2) == np.zeros(r, dtype=int)):
    print(f"Syndrome = {(broken_key_word @ h_matrix) % 2}")
    print(f"Sent word = {key_word}")
    print(f"Broken word = {broken_key_word}")
else:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r3_three_second = all(key_word == repaired_word)


print(f"r3 one err = {r3_one}")
print(f"r3 two err = {r3_two}")
print(f"r3 three first err = {r3_three_first}")
print(f"r3 three second err = {r3_three_second}")

Syndrome = [0 0 0]
Sent word = [0 0 0 0 0 0 0]
Broken word = [1 1 1 0 0 0 0]
r3 one err = True
r3 two err = False
r3 three first err = False
r3 three second err = False


---
##### r = 2

In [116]:
r = 2


h_matrix = create_h_matrix(r)
g_matrix = create_g_matrix(r)
syndromes_ones = create_syndrome_ones_table(h_matrix)


word = np.zeros(2** r - 1 - r, dtype=int)

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = 1

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r2_one = all(key_word == repaired_word)


# Двукратная ошибка
# r = 2
word = np.zeros(2**r - 1 - r, dtype=int)

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r2_two = all(key_word == repaired_word)


# Трёхкратная ошибка
# r = 2
word = np.zeros(2** r - 1 - r, dtype=int)

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[2] = (broken_key_word[2] + 1) % 2

if all(((broken_key_word @ h_matrix) % 2) == np.zeros(r, dtype=int)):
    print(f"Syndrome: {(broken_key_word @ h_matrix) % 2}")
    print(f"Sent word: {key_word}")
    print(f"Broken word: {broken_key_word}")
else:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r2_three = all(key_word == repaired_word)


print(f"r2 one err  \t = {r2_one}")
print(f"r2 two err  \t = {r2_two}")
print(f"r2 three err \t = {r2_three}")

Syndrome: [0 0]
Sent word: [0 0 0]
Broken word: [1 1 1]
r2 one err  	 = True
r2 two err  	 = False
r2 three err 	 = False


---
##### r = 4

In [117]:
r = 4


h_matrix = create_h_matrix(r)
g_matrix = create_g_matrix(r)
syndromes_ones = create_syndrome_ones_table(h_matrix)


word = np.zeros(2** r - 1 - r, dtype=int)

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = 1

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r4_one = all(key_word == repaired_word)


# Двукратная ошибка
# r = 4
word = np.zeros(2**r - 1 - r, dtype=int)

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r4_two = all(key_word == repaired_word)


# Трёхкратная ошибка (Снова с повторением действий)
# r = 4

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[3] = (broken_key_word[3] + 1) % 2

if all(((broken_key_word @ h_matrix) % 2) == np.zeros(r, dtype=int)):
    print(f"Syndrome: {(broken_key_word @ h_matrix) % 2}")
    print(f"Sent word: {key_word}")
    print(f"Broken word: {broken_key_word}")
else:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r4_three_first = all(key_word == repaired_word)


# И те же действия, но уже для другого исхода if.
word = np.zeros(2 ** r - 1 - r, dtype=int)

key_word = (word @ g_matrix) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[2] = (broken_key_word[2] + 1) % 2

if all(((broken_key_word @ h_matrix) % 2) == np.zeros(r, dtype=int)):
    print(f"Syndrome = {(broken_key_word @ h_matrix) % 2}")
    print(f"Sent word = {key_word}")
    print(f"Broken word = {broken_key_word}")
else:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r4_three_second = all(key_word == repaired_word)


print(f"r4 one err = {r4_one}")
print(f"r4 two err = {r4_two}")
print(f"r4 three first err = {r4_three_first}")
print(f"r4 three second err = {r4_three_second}")

Syndrome = [0 0 0 0]
Sent word = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Broken word = [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
r4 one err = True
r4 two err = False
r4 three first err = False
r4 three second err = False


#### 3.3 Написать функцию формирования порождающей и проверочной матриц расширенного кода Хэмминга (H*)
(2^r^ - 1,2^r^ − r − 1,3) на основе параметра r,
а также таблицы синдромов для всех однократных ошибок

In [118]:
def create_h_matrix_extended(h_matrix_local):
    '''
    Функция, возвращающая **расширенную** проверочную матрицу Хемминга
    :param h_matrix_local: матрица Хемминга
    :return: расширенная матрица Хемминга
    '''
    h_matrix_extended_local = np.zeros((h_matrix_local.shape[0] + 1, h_matrix_local.shape[1] + 1), dtype=int)
    h_matrix_extended_local[0:h_matrix_local.shape[0], 0:h_matrix_local.shape[1]] = h_matrix_local.copy()
    h_matrix_extended_local[:, h_matrix_extended_local.shape[1] - 1] = np.ones(h_matrix_extended_local.shape[0])
    return h_matrix_extended_local


def create_g_matrix_extended(g_matrix_local):
    '''
    Функция, возвращающая **расширенную** порождающую матрицу Хемминга
    :param g_matrix_local: матрица Хемминга
    :return: расширенная матрица Хемминга
    '''
    g_matrix_extended_local = np.zeros((g_matrix_local.shape[0], g_matrix_local.shape[1] + 1), dtype=int)
    g_matrix_extended_local[:, 0:g_matrix_local.shape[1]] = g_matrix_local.copy()
    for i in range(g_matrix_extended_local.shape[0]):
        if sum(g_matrix_extended_local[i]) % 2 == 1:
            g_matrix_extended_local[i, g_matrix_extended_local.shape[1] - 1] = 1
    return g_matrix_extended_local


# Теперь по порядку
r = 2

h_matrix = create_h_matrix(r)
g_matrix = create_g_matrix(r)

h_matrix_extended = create_h_matrix_extended(h_matrix)
g_matrix_extended = create_g_matrix_extended(g_matrix)


print("h extended matrix = ")
print(h_matrix_extended)
print("\ng extended matrix = ")
print(g_matrix_extended)

h extended matrix = 
[[1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 1]]

g extended matrix = 
[[1 1 1 1]]


#### 3.4. Провести исследование расширенного кода Хэмминга для одно-, двух-, трёх- и четырёхкратных ошибок для r = 2, 3, 4.

---
##### r = 2

In [119]:
# Однократная ошибка
# r = 2

r = 2


syndromes_ones = create_syndrome_ones_table(h_matrix_extended)


word = np.zeros(2** r - 1 - r, dtype=int)

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = 1

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r2_one = all(key_word == repaired_word)


# Двукратная ошибка
# r = 2

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2

try:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

    r2_two(key_word == repaired_word)
except KeyError:
    print(f"Syndrome {(broken_key_word @ h_matrix_extended) % 2} not exists")


# Трёхкратная ошибка
# r = 2

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[2] = (broken_key_word[2] + 1) % 2

if all(((broken_key_word @ h_matrix_extended) % 2) == np.zeros(r + 1, dtype=int)):
    print(f"Syndrome = {(broken_key_word @ h_matrix_extended) % 2}")
    print(f"Sent word = {key_word}")
    print(f"Broken word = {broken_key_word}")
else:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r2_three_first = all(key_word == repaired_word)


# Четырёхкратная (!) ошибка и её попытка исправления

word = np.zeros(2 ** r - 1 - r, dtype=int)

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[2] = (broken_key_word[2] + 1) % 2
broken_key_word[3] = (broken_key_word[3] + 1) % 2

if all(((broken_key_word @ h_matrix_extended) % 2) == np.zeros(r + 1, dtype=int)):
    print(f"Syndrome = {(broken_key_word @ h_matrix_extended) % 2}")
    print(f"Sent word = {key_word}")
    print(f"Broken word = {broken_key_word}")
else:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r2_four = all(key_word == repaired_word)


print(f"r2 one err  \t= {r2_one}")
print(f"r2 two err  \t= {r2_two}")
print(f"r2 three err \t= {r2_three}")
print(f"r2 four err \t= {r2_four}")

Syndrome [0 1 0] not exists
Syndrome = [0 0 0]
Sent word = [0 0 0 0]
Broken word = [1 1 1 1]
r2 one err  	= True
r2 two err  	= False
r2 three err 	= False
r2 four err 	= False


---

##### r = 3

In [120]:
# Однократная ошибка
# r = 3

r = 3

h_matrix = create_h_matrix(r)
g_matrix = create_g_matrix(r)

h_matrix_extended = create_h_matrix_extended(h_matrix)
g_matrix_extended = create_g_matrix_extended(g_matrix)

syndromes_ones = create_syndrome_ones_table(h_matrix_extended)

word = np.zeros(2** r - 1 - r, dtype=int)

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = 1

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r3_one = all(key_word == repaired_word)


# Двукратная ошибка
# r = 3

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2

try:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

    r3_two(key_word == repaired_word)
except KeyError:
    print(f"Syndrome {(broken_key_word @ h_matrix_extended) % 2} not exists")


# Трёхкратная ошибка
# r = 3

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[2] = (broken_key_word[2] + 1) % 2

if all(((broken_key_word @ h_matrix_extended) % 2) == np.zeros(r + 1, dtype=int)):
    print(f"Syndrome = {(broken_key_word @ h_matrix_extended) % 2}")
    print(f"Sent word = {key_word}")
    print(f"Broken word = {broken_key_word}")
else:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r3_three = all(key_word == repaired_word)


# Четырёхкратная ошибка
word = np.zeros(2 ** r - 1 - r, dtype=int)

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[2] = (broken_key_word[2] + 1) % 2
broken_key_word[3] = (broken_key_word[3] + 1) % 2

if all(((broken_key_word @ h_matrix_extended) % 2) == np.zeros(r + 1, dtype=int)):
    print(f"Syndrome = {(broken_key_word @ h_matrix_extended) % 2}")
    print(f"Sent word = {key_word}")
    print(f"Broken word = {broken_key_word}")
else:
    try:
        error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
        repaired_word = broken_key_word.copy()
        repaired_word[error_index] = (repaired_word[error_index] + 1) % 2
    except KeyError:
        print(f"Syndrome {(broken_key_word @ h_matrix_extended) % 2} doesn't exists")

r3_four = all(key_word == repaired_word)

print(f"r3 one err  \t= {r3_one}")
print(f"r3 two err  \t= {r3_two}")
print(f"r3 three err \t= {r3_three}")
print(f"r3 four err \t= {r3_four}")

Syndrome [1 1 0 0] not exists
Syndrome [1 1 1 0] doesn't exists
r3 one err  	= True
r3 two err  	= False
r3 three err 	= False
r3 four err 	= False


---

##### r = 4

In [121]:
r = 4

h_matrix = create_h_matrix(r)
h_matrix_extended = create_h_matrix_extended(h_matrix)

g_matrix = create_g_matrix(r)
g_matrix_extended = create_g_matrix_extended(g_matrix)

syndromes_ones = create_syndrome_ones_table(h_matrix_extended)


# Одна ошибка
word = np.zeros(2 ** r - 1 - r, dtype=int)

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = 1

error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
repaired_word = broken_key_word.copy()
repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r4_one = all(key_word == repaired_word)


# Две ошибки
word = np.zeros(2 ** r - 1 - r, dtype=int)

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2

try:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2
except KeyError:
    print(f"Syndrome {(broken_key_word @ h_matrix_extended) % 2} is not exists")

r4_two = all(key_word == repaired_word)


# Три ошибки
word = np.zeros(2 ** r - 1 - r, dtype=int)

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[2] = (broken_key_word[2] + 1) % 2

if all(((broken_key_word @ h_matrix_extended) % 2) == np.zeros(r + 1, dtype=int)):
    print(f"Syndrome = {(broken_key_word @ h_matrix_extended) % 2}")
    print(f"Sent word = {key_word}")
    print(f"Broken word = {broken_key_word}")
else:
    error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
    repaired_word = broken_key_word.copy()
    repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

r4_three = all(key_word == repaired_word)


# Четыре ошибки
word = np.zeros(2 ** r - 1 - r, dtype=int)

key_word = (word @ g_matrix_extended) % 2
broken_key_word = key_word.copy()
broken_key_word[0] = (broken_key_word[0] + 1) % 2
broken_key_word[1] = (broken_key_word[1] + 1) % 2
broken_key_word[2] = (broken_key_word[2] + 1) % 2
broken_key_word[3] = (broken_key_word[3] + 1) % 2

if all(((broken_key_word @ h_matrix_extended) % 2) == np.zeros(r + 1, dtype=int)):
    print(f"Syndrome = {(broken_key_word @ h_matrix_extended) % 2}")
    print(f"Sent word = {key_word}")
    print(f"Broken word = {broken_key_word}")
else:
    try:
        error_index = syndromes_ones[np.array_str((broken_key_word @ h_matrix_extended) % 2)]
        repaired_word = broken_key_word.copy()
        repaired_word[error_index] = (repaired_word[error_index] + 1) % 2

    except KeyError:
        print(f"Syndrome {(broken_key_word @ h_matrix_extended) % 2} is not in this reality")

r4_four = all(key_word == repaired_word)


print(f"r4 one err  \t= {r4_one}")
print(f"r4 two err  \t= {r4_two}")
print(f"r4 three err \t= {r4_three}")
print(f"r4 four err \t= {r4_four}")

Syndrome [0 1 1 0 0] is not exists
Syndrome [0 1 1 1 0] is not in this reality
r4 one err  	= True
r4 two err  	= True
r4 three err 	= False
r4 four err 	= False
