
# Теория Кодирования
## Лабораторная работа 4

От студента группы **6405**-010302
**Слеповичева Святослава**


---

### Задание
#### 4.1 Написать функцию формирования порождающей и проверочной матриц расширенного кода Голея.


In [130]:
import numpy as np
from itertools import product

In [131]:
def generate_golay_matrices():
    B = np.array([
        [1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
        [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
        [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
        [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
        [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
        [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
        [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
        [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
        [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
        [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
        [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
    ])

    G = np.hstack((np.eye(12, dtype=int), B))

    H = np.vstack((np.eye(12, dtype=int), B))

    return G, H, B

In [132]:
G, H, B = generate_golay_matrices()
print("Generator matrix G:\n", G)
print("\nParity-check matrix H:\n", H)

Generator matrix G:
 [[1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]]

Parity-check matrix H:
 [[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 0 0

---
#### 4.2. Провести исследование расширенного кода Голея для одно-, двух-, трёх- и четырёхкратных ошибок.


In [133]:
def simulate_errors(codeword, num_errors):
    """
    Функция, имитирующая внесение ошибок в кодовое слово
    :param codeword: исходное кодовое слово
    :param num_errors: количество ошибок, которые нужно внести
    :return: кодовое слово с внесенными ошибками
    """
    codeword_with_errors = codeword.copy()
    error_positions = np.random.choice(len(codeword), num_errors, replace=False)
    for pos in error_positions:
        codeword_with_errors[pos] ^= 1  # Flip the bit
    return codeword_with_errors


def syndrome_decode(received, H):
    """
    Функция, выполняющая синдромное декодирование для обнаружения и исправления ошибок
    :param received: принятое слово, которое может содержать ошибки
    :param H: проверочная матрица кода
    :return: синдром, вычисленный для принятого слова
    """
    syndrome = np.dot(received, H) % 2
    return syndrome


def research_golay_errors(G, H):
    """
    Ф-я исследует способность кода Голея исправлять ошибки
    :param G: порождающая матрица кода Голея
    :param H: И его проверочная матрица
    """
    message = np.random.randint(2, size=12)
    codeword = np.dot(message, G) % 2

    print(f"Original message: {message}")
    print(f"Codeword: {codeword}")

    words = [[0, 1] for _ in range(12)]
    words = np.array(list(product(*words)))

    words_dict = dict()

    for el in words:
        words_dict[np.array_str((el @ G) % 2)] = el

    for num_errors in range(1, 5):
        print(f"\nNumber of errors: {num_errors}")
        received_with_errors = simulate_errors(codeword, num_errors)
        print(f"Received with errors: {received_with_errors}")

        syndrome = np.array(syndrome_decode(received_with_errors, H))
        print(f"Syndrome: {syndrome}")

        u = np.array([])
        if sum(syndrome) <= 3:
            u = np.hstack((syndrome, np.zeros(12, dtype=int)))
        else:
            for i in range(B.shape[0]):
                if sum((syndrome + B[i]) % 2) <= 2:
                    e_i = np.zeros(12, dtype=int)
                    e_i[i] = 1
                    u = np.hstack(((syndrome + B[i]) % 2, e_i))
                    break
        if u.size == 0:
            syndrome_2 = (syndrome @ B) % 2
            if sum(syndrome_2) <= 3:
                u = np.hstack((np.zeros(12, dtype=int), syndrome_2))
            else:
                for i in range(B.shape[0]):
                    if sum((syndrome_2 + B[i]) % 2) <= 2:
                        e_i = np.zeros(12, dtype=int)
                        e_i[i] = 1
                        u = np.hstack((e_i, (syndrome_2 + B[i]) % 2))
                        break

        if u.size != 0:
            print(f"Source word: {words_dict[np.array_str((received_with_errors + u) % 2)]}")
        else:
            print("Error found but can not be fixed")


research_golay_errors(G, H)

Original message: [0 1 1 1 1 1 1 1 1 0 1 1]
Codeword: [0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 0 0 1 0 1 1]

Number of errors: 1
Received with errors: [0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 0 0 1 1 1 1]
Syndrome: [1 0 1 1 0 1 1 1 0 0 0 1]
Source word: [0 1 1 1 1 1 1 1 1 0 1 1]

Number of errors: 2
Received with errors: [0 1 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 0 1 1]
Syndrome: [1 1 0 0 1 1 0 1 1 0 1 1]
Source word: [0 1 1 1 1 1 1 1 1 0 1 1]

Number of errors: 3
Received with errors: [0 0 1 1 1 0 1 1 1 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1]
Syndrome: [0 1 0 0 0 1 0 0 0 0 1 0]
Source word: [0 1 1 1 1 1 1 1 1 0 1 1]

Number of errors: 4
Received with errors: [1 1 1 1 0 1 1 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1]
Syndrome: [1 0 0 0 1 0 0 1 0 0 1 0]
Error found but can not be fixed


---
#### 4.3 Написать функцию формирования порождающей и проверочных матриц кода Рида-Маллера 𝑅𝑀(𝑟,𝑚) на основе параметров 𝑟 и 𝑚.

In [134]:
def ReedMayer_G(r, m):
    if r == 0:
        return np.ones((1, 2**m), dtype=int)
    if r == m:
        return np.vstack((ReedMayer_G(m - 1, m), np.array([0 for _ in range(2 ** m - 1)] + [1])))

    mat = ReedMayer_G(r, m - 1)
    m2 = ReedMayer_G(r - 1, m - 1)
    return np.vstack((np.hstack((mat, mat)), np.hstack((np.zeros((m2.shape[0], mat.shape[1]), dtype=int), m2))))


r, m = 1, 3

Hs = []
H = np.array([[1, 1], [1, -1]])
for i in range(1, m + 1):
    Hs.append(np.kron(np.kron(np.eye(int(2**(m - i)), dtype=int), H), np.eye(int(2**(i - 1)), dtype=int)))


---
#### 4.4. Провести исследование кода Рида-Маллера 𝑅𝑀(1,3) для одно- и двукратных ошибок.

In [135]:
lists = [[0, 1], [0, 1], [0, 1], [0, 1]]
key_words = np.array(list(product(*lists)))
G_key_words = np.array([(el @ ReedMayer_G(r, m)) % 2 for el in key_words])
G_key_words

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 1, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 1, 1, 0]], dtype=int32)

In [136]:
k = np.array([1, 1, 0, 0])
w = (k @ ReedMayer_G(r, m)) % 2

# Однократные ошибки
w[0] = (w[0] + 1) % 2

candidats = []
dist = np.Infinity
for el in G_key_words:
    if sum((w + el) % 2) < dist:
        candidats.clear()
        candidats.append(el)
        dist = sum((w + el) % 2)
    elif sum((w + el) % 2) == dist:
        candidats.append(el)

if (len(candidats) == 1):
    w = candidats[0]
    w_cap = w.copy()
    w_cap[w_cap == 0] = -1

    for i in range(len(Hs)):
        w_cap = w_cap @ Hs[i]

    w_cap_abs = np.abs(w_cap)
    j = np.argmax(w_cap_abs)
    bin_j = bin(j)[2:]

    vj = "0"  * (m - len(bin_j))
    vj = vj + bin_j
    vj = vj[::-1]

    if(w_cap[j] > 0):
        fake_mes = np.array(list("1" + vj), dtype=int)
    else:
        fake_mes = np.array(list("0" + vj), dtype=int)
    print(f"Source word: {k}")
    print(f"Decoded word: {fake_mes}")
else:
    print("The error found but can not be fixed")

Source word: [1 1 0 0]
Decoded word: [1 1 0 0]


In [137]:
k = np.array([1, 1, 0, 0])
w = (k @ ReedMayer_G(r, m)) % 2

# Двукратные ошибки
w[0] = (w[0] + 1) % 2
w[1] = (w[1] + 1) % 2

candidats = []
dist = np.Infinity
for el in G_key_words:
    if sum((w + el) % 2) < dist:
        candidats.clear()
        candidats.append(el)
        dist = sum((w + el) % 2)
    elif sum((w + el) % 2) == dist:
        candidats.append(el)

if (len(candidats) == 1):
    w = candidats[0]
    w_cap = w.copy()
    w_cap[w_cap == 0] = -1

    for i in range(len(Hs)):
        w_cap = w_cap @ Hs[i]

    w_cap_abs = np.abs(w_cap)
    j = np.argmax(w_cap_abs)
    bin_j = bin(j)[2:]

    vj = "0"  * (m - len(bin_j))
    vj = vj + bin_j
    vj = vj[::-1]

    if(w_cap[j] > 0):
        fake_mes = np.array(list("1" + vj), dtype=int)
    else:
        fake_mes = np.array(list("0" + vj), dtype=int)
    print(f"Source word: {k}")
    print(f"Decoded word: {fake_mes}")
else:
    print("The error found but can not be fixed")

The error found but can not be fixed


---
#### 4.5. Провести исследование кода Рида-Маллера 𝑅𝑀(1,4) для одно-, двух-, трёх- и четырёхкратных ошибок.

In [138]:
r, m = 1, 4

Hs = []
H = np.array([[1, 1], [1, -1]])
for i in range(1, m + 1):
    Hs.append(np.kron(np.kron(np.eye(int(2**(m - i)), dtype=int), H), np.eye(int(2**(i - 1)), dtype=int)))

lists = [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]
key_words = np.array(list(product(*lists)))
G_key_words = np.array([(el @ ReedMayer_G(r, m)) % 2 for el in key_words])

In [139]:
k = np.array([1, 1, 1, 0, 0])
w = (k @ ReedMayer_G(r, m)) % 2

# Однократная
w[0] = (w[0] + 1) % 2

candidats = []
dist = np.Infinity
for el in G_key_words:
    if sum((w + el) % 2) < dist:
        candidats.clear()
        candidats.append(el)
        dist = sum((w + el) % 2)
    elif sum((w + el) % 2) == dist:
        candidats.append(el)

if (len(candidats) == 1):
    w = candidats[0]
    w_cap = w.copy()
    w_cap[w_cap == 0] = -1

    for i in range(len(Hs)):
        w_cap = w_cap @ Hs[i]

    w_cap_abs = np.abs(w_cap)
    j = np.argmax(w_cap_abs)
    bin_j = bin(j)[2:]

    vj = "0"  * (m - len(bin_j))
    vj = vj + bin_j
    vj = vj[::-1]

    if(w_cap[j] > 0):
        fake_mes = np.array(list("1" + vj), dtype=int)
    else:
        fake_mes = np.array(list("0" + vj), dtype=int)
    print(f"Source word: {k}")
    print(f"Decoded word: {fake_mes}")
else:
    print("The error found but can not be fixed")

Source word: [1 1 1 0 0]
Decoded word: [1 1 1 0 0]


In [140]:
k = np.array([1, 1, 1, 0, 0])
w = (k @ ReedMayer_G(r, m)) % 2

# Двукратная
w[0] = (w[0] + 1) % 2
w[1] = (w[1] + 1) % 2

candidats = []
dist = np.Infinity
for el in G_key_words:
    if sum((w + el) % 2) < dist:
        candidats.clear()
        candidats.append(el)
        dist = sum((w + el) % 2)
    elif sum((w + el) % 2) == dist:
        candidats.append(el)

if (len(candidats) == 1):
    w = candidats[0]
    w_cap = w.copy()
    w_cap[w_cap == 0] = -1

    for i in range(len(Hs)):
        w_cap = w_cap @ Hs[i]

    w_cap_abs = np.abs(w_cap)
    j = np.argmax(w_cap_abs)
    bin_j = bin(j)[2:]

    vj = "0"  * (m - len(bin_j))
    vj = vj + bin_j
    vj = vj[::-1]

    if(w_cap[j] > 0):
        fake_mes = np.array(list("1" + vj), dtype=int)
    else:
        fake_mes = np.array(list("0" + vj), dtype=int)
    print(f"Source word: {k}")
    print(f"Decoded word: {fake_mes}")
else:
    print("The error found but can not be fixed")

Source word: [1 1 1 0 0]
Decoded word: [1 1 1 0 0]


In [141]:
k = np.array([1, 1, 1, 0, 0])
w = (k @ ReedMayer_G(r, m)) % 2

# Трёхкратная ошибка
w[0] = (w[0] + 1) % 2
w[1] = (w[1] + 1) % 2
w[2] = (w[2] + 1) % 2

candidats = []
dist = np.Infinity
for el in G_key_words:
    if sum((w + el) % 2) < dist:
        candidats.clear()
        candidats.append(el)
        dist = sum((w + el) % 2)
    elif sum((w + el) % 2) == dist:
        candidats.append(el)

if (len(candidats) == 1):
    w = candidats[0]
    w_cap = w.copy()
    w_cap[w_cap == 0] = -1

    for i in range(len(Hs)):
        w_cap = w_cap @ Hs[i]

    w_cap_abs = np.abs(w_cap)
    j = np.argmax(w_cap_abs)
    bin_j = bin(j)[2:]

    vj = "0"  * (m - len(bin_j))
    vj = vj + bin_j
    vj = vj[::-1]

    if(w_cap[j] > 0):
        fake_mes = np.array(list("1" + vj), dtype=int)
    else:
        fake_mes = np.array(list("0" + vj), dtype=int)
    print(f"Source word: {k}")
    print(f"Decoded word: {fake_mes}")
else:
    print("The error found but can not be fixed")

Source word: [1 1 1 0 0]
Decoded word: [1 1 1 0 0]


In [142]:
k = np.array([1, 1, 1, 0, 0])
w = (k @ ReedMayer_G(r, m)) % 2

# Четырёхкратная ошибка
w[0] = (w[0] + 1) % 2
w[1] = (w[1] + 1) % 2
w[2] = (w[2] + 1) % 2
w[3] = (w[3] + 1) % 2

candidats = []
dist = np.Infinity
for el in G_key_words:
    if sum((w + el) % 2) < dist:
        candidats.clear()
        candidats.append(el)
        dist = sum((w + el) % 2)
    elif sum((w + el) % 2) == dist:
        candidats.append(el)

if (len(candidats) == 1):
    w = candidats[0]
    w_cap = w.copy()
    w_cap[w_cap == 0] = -1

    for i in range(len(Hs)):
        w_cap = w_cap @ Hs[i]

    w_cap_abs = np.abs(w_cap)
    j = np.argmax(w_cap_abs)
    bin_j = bin(j)[2:]

    vj = "0"  * (m - len(bin_j))
    vj = vj + bin_j
    vj = vj[::-1]

    if(w_cap[j] > 0):
        fake_mes = np.array(list("1" + vj), dtype=int)
    else:
        fake_mes = np.array(list("0" + vj), dtype=int)
    print(f"Source word: {k}")
    print(f"Decoded word: {fake_mes}")
else:
    print("The error found but can not be fixed")

The error found but can not be fixed
